update auto merge

diff --git a/.github/workflows/auto_merge.yml b/.github/workflows/auto_merge.yml
--- a/.github/workflows/auto_merge.yml
+++ b/.github/workflows/auto_merge.yml
@@ -6,9 +6,12 @@ on:
       - labeled
       - ready_for_review
       - synchronize
+      - auto_merge
   status:
     branches:
       - main
+      - test/pr-auto-merge
+      - dev
 
 jobs:
   auto_merge:
@@ -18,20 +21,32 @@ jobs:
       pull-requests: write
 
     steps:
-      # Checkout the repository
+      # 设置 Java 17 环境
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin' # 使用 Eclipse Temurin JDK
+          java-version: '17'      # 设置 Java 版本为 17
+
+      # 检出代码库
       - name: Checkout the repository
         uses: actions/checkout@v3
 
-      # 自动测试
+      # 运行测试
       - name: Run tests
+        id: run_tests
         run: mvn -B test --file pom.xml
 
       # 自动合并
       - name: Auto-merge PR
-        if: ${{ github.event.pull_request.head.sha == github.event.pull_request.mergeable && success() }}
+        if: ${{ steps.run_tests.outcome == 'success' }}
         run: |
-          curl -X PUT \
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github+json" \
           https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
-          -d '{"commit_title":"Auto-merged by GitHub Actions","merge_method":"merge"}'
+          -d '{"commit_title":"Auto-merged by GitHub Actions","merge_method":"merge"}')
+          if [ "$response" -ne 200 ]; then
+            echo "Failed to merge PR. HTTP status code: $response"
+            exit 1
+          fi
